version: "3.9"

services:
  tests:
    image: composer:2.1
    volumes:
      - ./:/app
    working_dir: /app
    command: >
      sh -c "rm -f ./composer.lock &&
             composer validate &&
             composer install &&
             php ./vendor/bin/phpinsights -v --no-interaction &&
             php ./vendor/bin/phpstan analyse --ansi --memory-limit 512M &&
             php ./vendor/bin/psalm &&
             php ./vendor/bin/pest --stop-on-failure"
