version: "3.9"

services:
  tests-7.4:
    volumes:
      - ./:/app
    tmpfs:
      - /app/vendor
    working_dir: /app
    build:
      context: .
      dockerfile: ./docker/php-7.4.dockerfile
  tests-8.0:
    volumes:
      - ./:/app
    tmpfs:
      - /app/vendor
    working_dir: /app
    build:
      context: .
      dockerfile: ./docker/php-8.0.dockerfile
  tests-8.1:
    volumes:
      - ./:/app
    tmpfs:
      - /app/vendor
    working_dir: /app
    build:
      context: .
      dockerfile: ./docker/php-8.1.dockerfile
