version: 2.1

commands:
  prepare:
    steps:
      - checkout
      - run: sudo composer self-update
      - restore_cache:
          keys:
            - composer-v1-{{ .Environment.CIRCLE_JOB }}-{{ checksum "composer.json" }}
            - composer-v1-{{ .Environment.CIRCLE_JOB }}
      - run: composer install -n --prefer-dist
      - run: composer update --prefer-dist --no-interaction
      - persist_to_workspace:
          root: .
          paths:
            - composer.*
            - .snyk
      - save_cache:
          key: composer-v1-{{ .Environment.CIRCLE_JOB }}-{{ checksum "composer.json" }}
          paths:
            - vendor
  run-quality-checks:
    steps:
      - run: php ./vendor/bin/phpinsights --no-interaction --min-quality=50 --min-complexity=50 --min-architecture=50 --min-style=5
  run-test-suite:
    steps:
      - run: php ./vendor/bin/pest --stop-on-failure --coverage-clover=build/coverage.xml
      - store_artifacts:
          path: build/coverage.xml

jobs:
  php_7_4:
    docker:
      - image: circleci/php:7.4
    steps:
      - prepare
      - run-quality-checks
      - run-test-suite
  php_8_0:
    docker:
      - image: circleci/php:8.0
    steps:
      - prepare
      - run-quality-checks
      - run-test-suite
  snyk:
    docker:
      - image: snyk/snyk-cli:composer
    steps:
      - attach_workspace:
          at: .
      - run: snyk test
      - run:
          command: |
            if [[ "${CIRCLE_BRANCH}" == "master" ]]
            then
            snyk monitor --org=auth0-sdks
            fi
          when: always

workflows:
  test-php-versions:
    jobs:
      - php_7_4
      - php_8_0
  vulnerability-check:
    jobs:
      - php_7_4
      - snyk:
          filters:
            branches:
              only:
                - master
          context: snyk-env
          requires:
            - php_7_4
