name: Report a Bug
description: Encountering unexpected problems or unintended behavior? Let us know!
labels: ["Type: 🐞 Bug (Unconfirmed)", "Status: 👀 Reviewing"]

body:
  - type: markdown
    attributes:
      value: Thanks for taking the time to help us improve this SDK!

  - type: dropdown
    id: sdk
    attributes:
      label: SDK Version
      description: What version of our SDK are you running? (`composer show | grep auth0/auth0-php`)
      options:
        - 8.3
        - 8.2
        - 8.1
        - 8.0
        - Other (specify in 'additional context')
    validations:
      required: true

  - type: dropdown
    id: php
    attributes:
      label: PHP Version
      description: What version of PHP are you running? (`php -v`)
      options:
        - PHP 8.2
        - PHP 8.1
        - PHP 8.0
        - Other (specify in 'additional context')
    validations:
      required: true

  - type: textarea
    id: bug-description
    attributes:
      label: What happened?
      description: Also tell us, what did you expect to happen?
    validations:
      required: true

  - type: textarea
    id: bug-reproduction
    attributes:
      label: How can we reproduce this issue?
      description: Detail the steps taken to reproduce this error, and whether this can be reproduced consistently or if it is intermittent.
    validations:
      required: true

  - type: textarea
    id: context
    attributes:
      label: Additional context
      description: Add any other context about the problem here.
