blank_issues_enabled: false
contact_links:
  - name: Community Support
    url: https://community.auth0.com/tag/auth0-php
    about: Please ask general usage questions here.
  - name: Responsible Disclosure Program
    url: https://auth0.com/whitehat
    about: Please do not report security vulnerabilities on the public GitHub issue tracker. The Responsible Disclosure Program details the procedure for disclosing security issues.
