name: Suggest a Feature
description: Help us improve the SDK by suggest new features and improvements.

body:
  - type: markdown
    attributes:
      value: Thanks for taking the time to help us improve this SDK!

  - type: checkboxes
      id: checklist
      attributes:
        label: Checklist
        options:
          - label: I agree to adhere to the [Auth0 General Contribution Guidelines](https://github.com/auth0/open-source-template/blob/master/GENERAL-CONTRIBUTING.md).
            required: true
          - label: I agree to uphold the [Auth0 Code of Conduct](https://github.com/auth0/open-source-template/blob/master/CODE-OF-CONDUCT.md).
            required: true

  - type: textarea
    id: feature-description
    attributes:
      label: Description
      description: Please provide a summary of the change you'd like us to consider, including any relevant context
    validations:
      required: true
