name: Suggest a Feature
description: Help us improve the SDK by suggest new features and improvements.
labels: ["Type: ⭐ Enhancement", "Status: 👀 Reviewing"]

body:
  - type: markdown
    attributes:
      value: Thanks for taking the time to help us improve this SDK!

  - type: textarea
    id: feature-description
    attributes:
      label: What should be added?
      description: How do you think this feature will improve the developer experience?
    validations:
      required: true
