name: Suggest a Feature
description: Help us improve the SDK by suggest new features and improvements.
labels: ["inbox"]

body:
  - type: markdown
    attributes:
      value: Thanks for taking the time to help us improve this SDK!

  - type: checkboxes
    id: checklist
    attributes:
      label: Checklist
      options:
        - label: The issue can be reproduced in a a sample app (either [webapp](https://github.com/auth0-samples/auth0-php-web-app) or [api](https://github.com/auth0-samples/auth0-php-api-samples)) (or N/A).
          required: true
        - label: I have looked into the [README](https://github.com/auth0/auth0-PHP#readme) and have not found a suitable solution or answer.
          required: true
        - label: I have looked into the [examples](https://github.com/auth0/auth0-PHP/blob/main/EXAMPLES.md) and have not found a suitable solution or answer.
          required: true
        - label: I have looked into the [API documentation](https://auth0.github.io/auth0-PHP/) and have not found a suitable solution or answer.
          required: true
        - label: I have searched the [issues](https://github.com/auth0/auth0-PHP/issues) and have not found a suitable solution or answer.
          required: true
        - label: I have searched the [Auth0 Community](https://community.auth0.com/tag/auth0-php) forums and have not found a suitable solution or answer.
          required: true
        - label: I agree to the terms within the [Auth0 Code of Conduct](https://github.com/auth0/open-source-template/blob/master/CODE-OF-CONDUCT.md).
          required: true

  - type: textarea
    id: feature-description
    attributes:
      label: Description
      description: Please provide a summary of the change you'd like us to consider, including any relevant context
    validations:
      required: true
