<?php

namespace Auth0\SDK\API\Management\Users\Identities;

use Psr\Http\Client\ClientInterface;
use Auth0\SDK\API\Management\Core\Client\RawClient;
use Auth0\SDK\API\Management\Users\Identities\Requests\LinkUserIdentityRequestContent;
use Auth0\SDK\API\Management\Types\UserIdentity;
use Auth0\SDK\API\Management\Exceptions\Auth0Exception;
use Auth0\SDK\API\Management\Exceptions\Auth0ApiException;
use Auth0\SDK\API\Management\Core\Json\JsonApiRequest;
use Auth0\SDK\API\Management\Environments;
use Auth0\SDK\API\Management\Core\Client\HttpMethod;
use Auth0\SDK\API\Management\Core\Json\JsonDecoder;
use JsonException;
use Psr\Http\Client\ClientExceptionInterface;
use Auth0\SDK\API\Management\Types\UserIdentityProviderEnum;
use Auth0\SDK\API\Management\Types\DeleteUserIdentityResponseContentItem;

class IdentitiesClient implements IdentitiesClientInterface
{
    /**
     * @var array{
     *   baseUrl?: string,
     *   client?: ClientInterface,
     *   maxRetries?: int,
     *   timeout?: float,
     *   headers?: array<string, string>,
     * } $options @phpstan-ignore-next-line Property is used in endpoint methods via HttpEndpointGenerator
     */
    private array $options;

    /**
     * @var RawClient $client
     */
    private RawClient $client;

    /**
     * @param RawClient $client
     * @param ?array{
     *   baseUrl?: string,
     *   client?: ClientInterface,
     *   maxRetries?: int,
     *   timeout?: float,
     *   headers?: array<string, string>,
     * } $options
     */
    public function __construct(
        RawClient $client,
        ?array $options = null,
    ) {
        $this->client = $client;
        $this->options = $options ?? [];
    }

    /**
     * Link two user accounts together forming a primary and secondary relationship. On successful linking, the endpoint returns the new array of the primary account identities.
     *
     * Note: There are two ways of invoking the endpoint:
     *
     * - With the authenticated primary account's JWT in the Authorization header, which has the `update:current_user_identities` scope:
     *
     *   ```http
     *   POST /api/v2/users/PRIMARY_ACCOUNT_USER_ID/identities
     *   Authorization: "Bearer PRIMARY_ACCOUNT_JWT"
     *   {
     *     "link_with": "SECONDARY_ACCOUNT_JWT"
     *   }
     *   ```
     *
     *   In this case, only the `link_with` param is required in the body, which also contains the JWT obtained upon the secondary account's authentication.
     *
     * - With a token generated by the API V2 containing the `update:users` scope:
     *
     *   ```http
     *   POST /api/v2/users/PRIMARY_ACCOUNT_USER_ID/identities
     *   Authorization: "Bearer YOUR_API_V2_TOKEN"
     *   {
     *     "provider": "SECONDARY_ACCOUNT_PROVIDER",
     *     "connection_id": "SECONDARY_ACCOUNT_CONNECTION_ID(OPTIONAL)",
     *     "user_id": "SECONDARY_ACCOUNT_USER_ID"
     *   }
     *   ```
     *
     *   In this case you need to send `provider` and `user_id` in the body. Optionally you can also send the `connection_id` param which is suitable for identifying a particular database connection for the 'auth0' provider.
     *
     * @param string $id ID of the primary user account to link a second user account to.
     * @param LinkUserIdentityRequestContent $request
     * @param ?array{
     *   baseUrl?: string,
     *   maxRetries?: int,
     *   timeout?: float,
     *   headers?: array<string, string>,
     *   queryParameters?: array<string, mixed>,
     *   bodyProperties?: array<string, mixed>,
     * } $options
     * @return ?array<UserIdentity>
     * @throws Auth0Exception
     * @throws Auth0ApiException
     */
    public function link(string $id, LinkUserIdentityRequestContent $request = new LinkUserIdentityRequestContent(), ?array $options = null): ?array
    {
        $options = array_merge($this->options, $options ?? []);
        try {
            $response = $this->client->sendRequest(
                new JsonApiRequest(
                    baseUrl: $options['baseUrl'] ?? $this->client->options['baseUrl'] ?? Environments::Default_->value,
                    path: "users/{$id}/identities",
                    method: HttpMethod::POST,
                    body: $request,
                ),
                $options,
            );
            $statusCode = $response->getStatusCode();
            if ($statusCode >= 200 && $statusCode < 400) {
                $json = $response->getBody()->getContents();
                if (empty($json)) {
                    return null;
                }
                return JsonDecoder::decodeArray($json, [UserIdentity::class]); // @phpstan-ignore-line
            }
        } catch (JsonException $e) {
            throw new Auth0Exception(message: "Failed to deserialize response: {$e->getMessage()}", previous: $e);
        } catch (ClientExceptionInterface $e) {
            throw new Auth0Exception(message: $e->getMessage(), previous: $e);
        }
        throw new Auth0ApiException(
            message: 'API request failed',
            statusCode: $statusCode,
            body: $response->getBody()->getContents(),
        );
    }

    /**
     * Unlink a specific secondary account from a target user. This action requires the ID of both the target user and the secondary account.
     *
     * Unlinking the secondary account removes it from the identities array of the target user and creates a new standalone profile for the secondary account. To learn more, review [Unlink User Accounts](https://auth0.com/docs/manage-users/user-accounts/user-account-linking/unlink-user-accounts).
     *
     * @param string $id ID of the primary user account.
     * @param value-of<UserIdentityProviderEnum> $provider Identity provider name of the secondary linked account (e.g. `google-oauth2`).
     * @param string $userId ID of the secondary linked account (e.g. `123456789081523216417` part after the `|` in `google-oauth2|123456789081523216417`).
     * @param ?array{
     *   baseUrl?: string,
     *   maxRetries?: int,
     *   timeout?: float,
     *   headers?: array<string, string>,
     *   queryParameters?: array<string, mixed>,
     *   bodyProperties?: array<string, mixed>,
     * } $options
     * @return ?array<DeleteUserIdentityResponseContentItem>
     * @throws Auth0Exception
     * @throws Auth0ApiException
     */
    public function delete(string $id, string $provider, string $userId, ?array $options = null): ?array
    {
        $options = array_merge($this->options, $options ?? []);
        try {
            $response = $this->client->sendRequest(
                new JsonApiRequest(
                    baseUrl: $options['baseUrl'] ?? $this->client->options['baseUrl'] ?? Environments::Default_->value,
                    path: "users/{$id}/identities/{$provider}/{$userId}",
                    method: HttpMethod::DELETE,
                ),
                $options,
            );
            $statusCode = $response->getStatusCode();
            if ($statusCode >= 200 && $statusCode < 400) {
                $json = $response->getBody()->getContents();
                if (empty($json)) {
                    return null;
                }
                return JsonDecoder::decodeArray($json, [DeleteUserIdentityResponseContentItem::class]); // @phpstan-ignore-line
            }
        } catch (JsonException $e) {
            throw new Auth0Exception(message: "Failed to deserialize response: {$e->getMessage()}", previous: $e);
        } catch (ClientExceptionInterface $e) {
            throw new Auth0Exception(message: $e->getMessage(), previous: $e);
        }
        throw new Auth0ApiException(
            message: 'API request failed',
            statusCode: $statusCode,
            body: $response->getBody()->getContents(),
        );
    }
}
