<?php

declare(strict_types=1);

namespace Auth0\SDK\Exception;

/**
 * Represents all errors generated by SDK itself.
 *
 * @codeCoverageIgnore
 */
interface Auth0Exception extends \Throwable
{
    final public function __construct(
        string $message,
        int $code = 0,
        ?\Throwable $previous = null
    ) {
        $backtrace = debug_backtrace(DEBUG_BACKTRACE_IGNORE_ARGS, 2)[1] ?? null;

        if ($backtrace !== null) {
            $this->file = $backtrace['file'];
            $this->line = $backtrace['line'];
        }

        parent::__construct($message, $code, $previous);
    }
}
