<?php

declare(strict_types=1);

namespace Auth0\SDK\Exception;

/**
 * Represents all errors generated by SDK itself.
 */
class EmptyOrInvalidParameterException extends \Auth0\SDK\Exception\CoreException
{
    /**
     * EmptyOrInvalidParameterException constructor.
     *
     * @param string $parameter_name The parameter name that is missing or invalid.
     */
    public function __construct(
        string $parameter_name
    ) {
        parent::__construct('Empty or invalid ' . $parameter_name . '.');
    }
}
