<?php

namespace Auth0\SDK\Exception;

/**
 * Represents all errors generated by SDK itself.
 */
class InvalidPermissionsArrayException extends CoreException
{

    /**
     * InvalidPermissionsArrayException constructor.
     */
    public function __construct()
    {
        parent::__construct(
            'Invalid or empty permissions array passed. 
                All permissions must include both permission_name and resource_server_identifier keys.'
        );
    }
}
