<?php

namespace Auth0\SDK\API\Management\Types;

use Auth0\SDK\API\Management\Core\Json\JsonSerializableType;
use Auth0\SDK\API\Management\Core\Json\JsonProperty;
use Auth0\SDK\API\Management\Core\Types\ArrayType;
use DateTime;
use Auth0\SDK\API\Management\Core\Types\Date;

/**
 * The successfully created authentication method.
 */
class UpdateUserAuthenticationMethodResponseContent extends JsonSerializableType
{
    /**
     * @var ?string $id The ID of the newly created authentication method (automatically generated by the application)
     */
    #[JsonProperty('id')]
    private ?string $id;

    /**
     * @var value-of<CreatedAuthenticationMethodTypeEnum> $type
     */
    #[JsonProperty('type')]
    private string $type;

    /**
     * @var ?string $name A human-readable label to identify the authentication method.
     */
    #[JsonProperty('name')]
    private ?string $name;

    /**
     * @var ?string $totpSecret Base32 encoded secret for TOTP generation
     */
    #[JsonProperty('totp_secret')]
    private ?string $totpSecret;

    /**
     * @var ?string $phoneNumber Applies to phone authentication methods only. The destination phone number used to send verification codes via text and voice.
     */
    #[JsonProperty('phone_number')]
    private ?string $phoneNumber;

    /**
     * @var ?string $email Applies to email authentication methods only. The email address used to send verification messages.
     */
    #[JsonProperty('email')]
    private ?string $email;

    /**
     * @var ?array<UserAuthenticationMethodProperties> $authenticationMethods
     */
    #[JsonProperty('authentication_methods'), ArrayType([UserAuthenticationMethodProperties::class])]
    private ?array $authenticationMethods;

    /**
     * @var ?value-of<PreferredAuthenticationMethodEnum> $preferredAuthenticationMethod
     */
    #[JsonProperty('preferred_authentication_method')]
    private ?string $preferredAuthenticationMethod;

    /**
     * @var ?string $keyId Applies to webauthn authentication methods only. The id of the credential.
     */
    #[JsonProperty('key_id')]
    private ?string $keyId;

    /**
     * @var ?string $publicKey Applies to webauthn authentication methods only. The public key.
     */
    #[JsonProperty('public_key')]
    private ?string $publicKey;

    /**
     * @var ?string $aaguid Applies to passkey authentication methods only. Authenticator Attestation Globally Unique Identifier.
     */
    #[JsonProperty('aaguid')]
    private ?string $aaguid;

    /**
     * @var ?string $relyingPartyIdentifier Applies to webauthn authentication methods only. The relying party identifier.
     */
    #[JsonProperty('relying_party_identifier')]
    private ?string $relyingPartyIdentifier;

    /**
     * @var ?bool $confirmed Whether the authentication method has been confirmed.
     */
    #[JsonProperty('confirmed')]
    private ?bool $confirmed;

    /**
     * @var ?DateTime $createdAt Authentication method creation date
     */
    #[JsonProperty('created_at'), Date(Date::TYPE_DATETIME)]
    private ?DateTime $createdAt;

    /**
     * @param array{
     *   type: value-of<CreatedAuthenticationMethodTypeEnum>,
     *   id?: ?string,
     *   name?: ?string,
     *   totpSecret?: ?string,
     *   phoneNumber?: ?string,
     *   email?: ?string,
     *   authenticationMethods?: ?array<UserAuthenticationMethodProperties>,
     *   preferredAuthenticationMethod?: ?value-of<PreferredAuthenticationMethodEnum>,
     *   keyId?: ?string,
     *   publicKey?: ?string,
     *   aaguid?: ?string,
     *   relyingPartyIdentifier?: ?string,
     *   confirmed?: ?bool,
     *   createdAt?: ?DateTime,
     * } $values
     */
    public function __construct(
        array $values,
    ) {
        $this->id = $values['id'] ?? null;
        $this->type = $values['type'];
        $this->name = $values['name'] ?? null;
        $this->totpSecret = $values['totpSecret'] ?? null;
        $this->phoneNumber = $values['phoneNumber'] ?? null;
        $this->email = $values['email'] ?? null;
        $this->authenticationMethods = $values['authenticationMethods'] ?? null;
        $this->preferredAuthenticationMethod = $values['preferredAuthenticationMethod'] ?? null;
        $this->keyId = $values['keyId'] ?? null;
        $this->publicKey = $values['publicKey'] ?? null;
        $this->aaguid = $values['aaguid'] ?? null;
        $this->relyingPartyIdentifier = $values['relyingPartyIdentifier'] ?? null;
        $this->confirmed = $values['confirmed'] ?? null;
        $this->createdAt = $values['createdAt'] ?? null;
    }

    /**
     * @return ?string
     */
    public function getId(): ?string
    {
        return $this->id;
    }

    /**
     * @param ?string $value
     */
    public function setId(?string $value = null): self
    {
        $this->id = $value;
        $this->_setField('id');
        return $this;
    }

    /**
     * @return value-of<CreatedAuthenticationMethodTypeEnum>
     */
    public function getType(): string
    {
        return $this->type;
    }

    /**
     * @param value-of<CreatedAuthenticationMethodTypeEnum> $value
     */
    public function setType(string $value): self
    {
        $this->type = $value;
        $this->_setField('type');
        return $this;
    }

    /**
     * @return ?string
     */
    public function getName(): ?string
    {
        return $this->name;
    }

    /**
     * @param ?string $value
     */
    public function setName(?string $value = null): self
    {
        $this->name = $value;
        $this->_setField('name');
        return $this;
    }

    /**
     * @return ?string
     */
    public function getTotpSecret(): ?string
    {
        return $this->totpSecret;
    }

    /**
     * @param ?string $value
     */
    public function setTotpSecret(?string $value = null): self
    {
        $this->totpSecret = $value;
        $this->_setField('totpSecret');
        return $this;
    }

    /**
     * @return ?string
     */
    public function getPhoneNumber(): ?string
    {
        return $this->phoneNumber;
    }

    /**
     * @param ?string $value
     */
    public function setPhoneNumber(?string $value = null): self
    {
        $this->phoneNumber = $value;
        $this->_setField('phoneNumber');
        return $this;
    }

    /**
     * @return ?string
     */
    public function getEmail(): ?string
    {
        return $this->email;
    }

    /**
     * @param ?string $value
     */
    public function setEmail(?string $value = null): self
    {
        $this->email = $value;
        $this->_setField('email');
        return $this;
    }

    /**
     * @return ?array<UserAuthenticationMethodProperties>
     */
    public function getAuthenticationMethods(): ?array
    {
        return $this->authenticationMethods;
    }

    /**
     * @param ?array<UserAuthenticationMethodProperties> $value
     */
    public function setAuthenticationMethods(?array $value = null): self
    {
        $this->authenticationMethods = $value;
        $this->_setField('authenticationMethods');
        return $this;
    }

    /**
     * @return ?value-of<PreferredAuthenticationMethodEnum>
     */
    public function getPreferredAuthenticationMethod(): ?string
    {
        return $this->preferredAuthenticationMethod;
    }

    /**
     * @param ?value-of<PreferredAuthenticationMethodEnum> $value
     */
    public function setPreferredAuthenticationMethod(?string $value = null): self
    {
        $this->preferredAuthenticationMethod = $value;
        $this->_setField('preferredAuthenticationMethod');
        return $this;
    }

    /**
     * @return ?string
     */
    public function getKeyId(): ?string
    {
        return $this->keyId;
    }

    /**
     * @param ?string $value
     */
    public function setKeyId(?string $value = null): self
    {
        $this->keyId = $value;
        $this->_setField('keyId');
        return $this;
    }

    /**
     * @return ?string
     */
    public function getPublicKey(): ?string
    {
        return $this->publicKey;
    }

    /**
     * @param ?string $value
     */
    public function setPublicKey(?string $value = null): self
    {
        $this->publicKey = $value;
        $this->_setField('publicKey');
        return $this;
    }

    /**
     * @return ?string
     */
    public function getAaguid(): ?string
    {
        return $this->aaguid;
    }

    /**
     * @param ?string $value
     */
    public function setAaguid(?string $value = null): self
    {
        $this->aaguid = $value;
        $this->_setField('aaguid');
        return $this;
    }

    /**
     * @return ?string
     */
    public function getRelyingPartyIdentifier(): ?string
    {
        return $this->relyingPartyIdentifier;
    }

    /**
     * @param ?string $value
     */
    public function setRelyingPartyIdentifier(?string $value = null): self
    {
        $this->relyingPartyIdentifier = $value;
        $this->_setField('relyingPartyIdentifier');
        return $this;
    }

    /**
     * @return ?bool
     */
    public function getConfirmed(): ?bool
    {
        return $this->confirmed;
    }

    /**
     * @param ?bool $value
     */
    public function setConfirmed(?bool $value = null): self
    {
        $this->confirmed = $value;
        $this->_setField('confirmed');
        return $this;
    }

    /**
     * @return ?DateTime
     */
    public function getCreatedAt(): ?DateTime
    {
        return $this->createdAt;
    }

    /**
     * @param ?DateTime $value
     */
    public function setCreatedAt(?DateTime $value = null): self
    {
        $this->createdAt = $value;
        $this->_setField('createdAt');
        return $this;
    }

    /**
     * @return string
     */
    public function __toString(): string
    {
        return $this->toJson();
    }
}
