name: Labels

on:
  pull_request_target:
    types:
      [
        opened,
        closed,
        reopened,
        converted_to_draft,
        review_requested,
        review_requested_removed,
        synchronize,
      ]

jobs:
  remove_labels:
    runs-on: ubuntu-latest

    permissions:
      issues: write
      pull-requests: write

    steps:
      - uses: actions/github-script@v6
        with:
          script: |
            // this gets the number at the end of the content URL, which should be the issue/PR number
            const issue_num = context.payload.project_card.content_url.split('/').pop()

            github.rest.issues.removeLabel({
              issue_number: issue_num,
              owner: context.repo.owner,
              repo: context.repo.repo,
              name: ["Status: 🤞 Run Tests"]
            })
