name: Analysis

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  pest:
    name: Pest
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: true
      max-parallel: 10
      matrix:
        php: ["7.4", "8.0", "8.1", "8.2"]
        os: ["ubuntu-latest", "windows-latest", "macos-latest"]
        prefer: ["lowest", "stable"]

    steps:
      - name: Set up PHP ${{ matrix.php }} (${{ matrix.os }})
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php }}
          coverage: pcov
          extensions: mbstring
        env:
          update: true
          COMPOSER_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Checkout code
        uses: actions/checkout@v3

      - name: Get composer cache directory
        id: composer-cache
        run: echo "::set-output name=dir::$(composer config cache-files-dir)"

      - name: Cache dependencies
        uses: actions/cache@v2
        with:
          path: ${{ steps.composer-cache.outputs.dir }}
          key: ${{ runner.os }}-${{ matrix.prefer }}-${{ matrix.php }}-composer-${{ hashFiles('**/composer.json') }}
          restore-keys: ${{ runner.os }}-${{ matrix.prefer }}-${{ matrix.php }}-composer-

      - name: Install (lowest) dependencies with composer
        if: (matrix.prefer == 'lowest' && matrix.php != '7.4')
        run: composer update --no-ansi --no-interaction --no-progress --prefer-dist --prefer-lowest

      - name: Install (stable) dependencies with composer
        if: (matrix.prefer == 'stable' || matrix.php == '7.4')
        run: composer update --no-ansi --no-interaction --no-progress --prefer-dist

      - name: Install Pest
        run: composer require pestphp/pest:* --with-all-dependencies

      - name: Prepare configuration
        run: mv $GITHUB_WORKSPACE/.github/workflows-configs/phpunit.xml.dist $GITHUB_WORKSPACE/phpunit.xml.dist

      - name: Execute Pest
        run: vendor/bin/pest --ci --coverage --coverage-clover coverage/coverage.xml

      - if: (matrix.php == '8.1' && matrix.os == 'ubuntu-latest' && matrix.prefer == 'stable')
        name: Upload coverage file
        uses: actions/upload-artifact@v3
        with:
          name: code-coverage-report
          path: coverage/coverage.xml

  codecov:
    name: Codecov
    runs-on: ubuntu-latest
    needs: pest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name:
        uses: actions/download-artifact@v3
        with:
          name: code-coverage-report
          path: coverage/coverage.xml

      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v2
        with:
          directory: coverage

  phpstan:
    name: PHPStan
    runs-on: ubuntu-latest
    strategy:
      fail-fast: true
      max-parallel: 10
      matrix:
        php: ["7.4", "8.0", "8.1", "8.2"]

    steps:
      - name: Set up PHP ${{ matrix.php }}
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php }}
          coverage: none
          extensions: mbstring
        env:
          update: true
          COMPOSER_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Checkout code
        uses: actions/checkout@v3

      - name: Get composer cache directory
        id: composer-cache
        run: echo "::set-output name=dir::$(composer config cache-files-dir)"

      - name: Cache dependencies
        uses: actions/cache@v2
        with:
          path: ${{ steps.composer-cache.outputs.dir }}
          key: ${{ runner.os }}-stable-${{ matrix.php }}-composer-${{ hashFiles('**/composer.json') }}
          restore-keys: ${{ runner.os }}-stable-${{ matrix.php }}-composer-

      - name: Install dependencies
        run: composer update --no-ansi --no-interaction --no-progress --prefer-dist

      - name: Install PHPStan
        run: composer require phpstan/phpstan:* --with-all-dependencies

      - name: Install PHPStan strict rules
        run: composer require phpstan/phpstan-strict-rules:* --with-all-dependencies

      - name: Install PHPCS
        run: composer require squizlabs/php_codesniffer:* --with-all-dependencies

      - name: Prepare configuration
        run: mv $GITHUB_WORKSPACE/.github/workflows-configs/phpstan.neon.dist $GITHUB_WORKSPACE/phpstan.neon.dist

      - name: Execute PHPStan
        run: vendor/bin/phpstan analyze --no-progress

  psalm:
    name: Psalm
    runs-on: ubuntu-latest
    strategy:
      fail-fast: true
      max-parallel: 10
      matrix:
        php: ["7.4", "8.0", "8.1"]

    steps:
      - name: Set up PHP ${{ matrix.php }}
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php }}
          coverage: none
          extensions: mbstring
        env:
          update: true
          COMPOSER_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Checkout code
        uses: actions/checkout@v3

      - name: Get composer cache directory
        id: composer-cache
        run: echo "::set-output name=dir::$(composer config cache-files-dir)"

      - name: Cache dependencies
        uses: actions/cache@v2
        with:
          path: ${{ steps.composer-cache.outputs.dir }}
          key: ${{ runner.os }}-stable-${{ matrix.php }}-composer-${{ hashFiles('**/composer.json') }}
          restore-keys: ${{ runner.os }}-stable-${{ matrix.php }}-composer-

      - name: Install dependencies
        run: composer update --no-ansi --no-interaction --no-progress --prefer-dist

      - name: Install Psalm
        run: composer require vimeo/psalm:* --with-all-dependencies

      - name: Prepare configuration
        run: mv $GITHUB_WORKSPACE/.github/workflows-configs/psalm.xml.dist $GITHUB_WORKSPACE/psalm.xml.dist

      - name: Execute Psalm
        run: vendor/bin/psalm

  pint:
    name: Laravel Pint
    runs-on: ubuntu-latest
    strategy:
      fail-fast: true
      max-parallel: 10
      matrix:
        php: ["8.0", "8.1", "8.2"]

    steps:
      - name: Set up PHP ${{ matrix.php }}
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php }}
          coverage: none
          extensions: mbstring
        env:
          update: true
          COMPOSER_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Checkout code
        uses: actions/checkout@v3

      - name: Get composer cache directory
        id: composer-cache
        run: echo "::set-output name=dir::$(composer config cache-files-dir)"

      - name: Cache dependencies
        uses: actions/cache@v2
        with:
          path: ${{ steps.composer-cache.outputs.dir }}
          key: ${{ runner.os }}-stable-${{ matrix.php }}-composer-${{ hashFiles('**/composer.json') }}
          restore-keys: ${{ runner.os }}-stable-${{ matrix.php }}-composer-

      - name: Install dependencies
        run: composer update --no-ansi --no-interaction --no-progress --prefer-dist

      - name: Install Laravel Pint
        run: composer require laravel/pint:* --dev --with-all-dependencies

      - name: Execute Laravel Pint
        run: vendor/bin/pint --config .\.github\workflows-configs\pint.json --test

  rector:
    name: Rector
    runs-on: ubuntu-latest
    strategy:
      fail-fast: true
      max-parallel: 10
      matrix:
        php: ["7.4", "8.0", "8.1", "8.2"]

    steps:
      - name: Set up PHP ${{ matrix.php }}
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php }}
          coverage: none
          extensions: mbstring
        env:
          update: true
          COMPOSER_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Checkout code
        uses: actions/checkout@v3

      - name: Get composer cache directory
        id: composer-cache
        run: echo "::set-output name=dir::$(composer config cache-files-dir)"

      - name: Cache dependencies
        uses: actions/cache@v2
        with:
          path: ${{ steps.composer-cache.outputs.dir }}
          key: ${{ runner.os }}-stable-${{ matrix.php }}-composer-${{ hashFiles('**/composer.json') }}
          restore-keys: ${{ runner.os }}-stable-${{ matrix.php }}-composer-

      - name: Install dependencies
        run: composer update --no-ansi --no-interaction --no-progress --prefer-dist

      - name: Install Rector
        run: composer require rector/rector:* --with-all-dependencies

      - name: Install PHPStan strict rules
        run: composer require phpstan/phpstan-strict-rules:* --with-all-dependencies

      - name: Install PHPCS
        run: composer require squizlabs/php_codesniffer:* --with-all-dependencies

      - name: Prepare configuration (1)
        run: mv $GITHUB_WORKSPACE/.github/workflows-configs/rector.php $GITHUB_WORKSPACE/rector.php

      - name: Prepare configuration (2)
        run: mv $GITHUB_WORKSPACE/.github/workflows-configs/phpstan.neon.dist $GITHUB_WORKSPACE/phpstan.neon.dist

      - name: Execute Rector
        run: vendor/bin/rector process src --dry-run
