name: Analysis

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  dependencies:
    name: Dependencies
    runs-on: ubuntu-latest

    strategy:
      max-parallel: 10
      matrix:
        php: ["7.4", "8.0", "8.1"]
        prefer: ["prefer-lowest", "prefer-stable"]

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up PHP ${{ matrix.php }} (${{ matrix.prefer }})
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php }}
          coverage: pcov
          extensions: mbstring
        env:
          update: true
          COMPOSER_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Get composer cache directory
        id: composer-cache
        run: echo "::set-output name=dir::$(composer config cache-files-dir)"

      - name: Cache dependencies
        uses: actions/cache@v2
        with:
          path: ${{ steps.composer-cache.outputs.dir }}
          key: ${{ matrix.php }}-composer-${{ matrix.prefer }}-${{ hashFiles('**/composer.json') }}

      - name: Install dependencies with composer
        run: composer update --no-ansi --no-interaction --no-progress --prefer-dist --${{ matrix.prefer }}

  pest:
    name: Pest
    runs-on: ${{ matrix.os }}
    continue-on-error: true
    needs:
      - dependencies

    strategy:
      max-parallel: 10
      matrix:
        php: ["7.4", "8.0", "8.1"]
        os: ["ubuntu-latest", "windows-latest"]
        prefer: ["prefer-lowest", "prefer-stable"]
        exclude:
          - php: "7.4"
            os: ubuntu-latest
            prefer: "prefer-lowest"
          - php: "7.4"
            os: windows-latest
            prefer: "prefer-lowest"

    steps:
      - name: Set up PHP ${{ matrix.php }} (${{ matrix.os }})
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php }}
          coverage: pcov
          extensions: mbstring
        env:
          update: true
          COMPOSER_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Checkout code
        uses: actions/checkout@v3

      - name: Get composer cache directory
        id: composer-cache
        run: echo "::set-output name=dir::$(composer config cache-files-dir)"

      - name: Cache dependencies
        uses: actions/cache@v2
        with:
          path: ${{ steps.composer-cache.outputs.dir }}
          key: ${{ matrix.php }}-composer-${{ matrix.prefer }}-${{ hashFiles('**/composer.json') }}
          restore-keys: ${{ matrix.php }}-composer-${{ matrix.prefer }}-${{ hashFiles('**/composer.json') }}

      - name: Install dependencies with composer
        run: composer install --prefer-dist

      - name: Prepare configuration
        run: mv .github/workflows-configs/phpunit.xml.dist phpunit.xml.dist

      - name: Execute Pest
        run: vendor/bin/pest --coverage-clover coverage/coverage.xml

      - if: (matrix.php == '8.1' && matrix.os == 'ubuntu-latest' && matrix.prefer == 'prefer-stable')
        name: Store coverage file
        uses: actions/upload-artifact@v3
        with:
          name: code-coverage-report
          path: coverage/coverage.xml

  codecov:
    name: Codecov
    runs-on: ubuntu-latest
    needs:
      - pest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Recover code coverage file from Pest run
        uses: actions/download-artifact@v3
        with:
          name: code-coverage-report
          path: coverage/coverage.xml

      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v2
        with:
          directory: coverage

  phpstan:
    name: PHPStan
    runs-on: ubuntu-latest
    needs:
      - dependencies

    strategy:
      fail-fast: true
      max-parallel: 10
      matrix:
        php: ["7.4", "8.0", "8.1"]

    steps:
      - name: Set up PHP ${{ matrix.php }}
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php }}
          coverage: none
          extensions: mbstring
        env:
          update: true
          COMPOSER_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Checkout code
        uses: actions/checkout@v3

      - name: Get composer cache directory
        id: composer-cache
        run: echo "::set-output name=dir::$(composer config cache-files-dir)"

      - name: Cache dependencies
        uses: actions/cache@v2
        with:
          path: ${{ steps.composer-cache.outputs.dir }}
          key: ${{ matrix.php }}-composer-prefer-stable-${{ hashFiles('**/composer.json') }}
          restore-keys: ${{ matrix.php }}-composer-prefer-stable-${{ hashFiles('**/composer.json') }}

      - name: Install dependencies
        run: composer install --prefer-dist

      - name: Prepare configuration
        run: mv .github/workflows-configs/phpstan.neon.dist phpstan.neon.dist

      - name: Execute PHPStan
        run: vendor/bin/phpstan analyze --no-progress

  psalm:
    name: Psalm
    runs-on: ubuntu-latest
    needs:
      - dependencies

    strategy:
      fail-fast: true
      max-parallel: 10
      matrix:
        php: ["7.4", "8.0", "8.1"]

    steps:
      - name: Set up PHP ${{ matrix.php }}
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php }}
          coverage: none
          extensions: mbstring
        env:
          update: true
          COMPOSER_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Checkout code
        uses: actions/checkout@v3

      - name: Get composer cache directory
        id: composer-cache
        run: echo "::set-output name=dir::$(composer config cache-files-dir)"

      - name: Cache dependencies
        uses: actions/cache@v2
        with:
          path: ${{ steps.composer-cache.outputs.dir }}
          key: ${{ matrix.php }}-composer-prefer-stable-${{ hashFiles('**/composer.json') }}
          restore-keys: ${{ matrix.php }}-composer-prefer-stable-${{ hashFiles('**/composer.json') }}

      - name: Install dependencies
        run: composer install --prefer-dist

      - name: Prepare configuration
        run: mv .github/workflows-configs/psalm.xml.dist psalm.xml.dist

      - name: Execute Psalm
        run: vendor/bin/psalm

  pint:
    name: Laravel Pint
    runs-on: ubuntu-latest
    needs:
      - dependencies

    strategy:
      fail-fast: true
      max-parallel: 10
      matrix:
        php: ["8.0", "8.1"]

    steps:
      - name: Set up PHP ${{ matrix.php }}
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php }}
          coverage: none
          extensions: mbstring
        env:
          update: true
          COMPOSER_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Checkout code
        uses: actions/checkout@v3

      - name: Get composer cache directory
        id: composer-cache
        run: echo "::set-output name=dir::$(composer config cache-files-dir)"

      - name: Cache dependencies
        uses: actions/cache@v2
        with:
          path: ${{ steps.composer-cache.outputs.dir }}
          key: ${{ matrix.php }}-composer-prefer-stable-${{ hashFiles('**/composer.json') }}
          restore-keys: ${{ matrix.php }}-composer-prefer-stable-${{ hashFiles('**/composer.json') }}

      - name: Install dependencies
        run: composer install --prefer-dist

      - name: Install Laravel Pint
        run: composer require laravel/pint:* --dev --with-all-dependencies

      - name: Execute Laravel Pint
        run: vendor/bin/pint --config .\.github\workflows-configs\pint.json --test

  rector:
    name: Rector
    runs-on: ubuntu-latest
    needs:
      - dependencies

    strategy:
      fail-fast: true
      max-parallel: 10
      matrix:
        php: ["7.4", "8.0", "8.1"]

    steps:
      - name: Set up PHP ${{ matrix.php }}
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php }}
          coverage: none
          extensions: mbstring
        env:
          update: true
          COMPOSER_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Checkout code
        uses: actions/checkout@v3

      - name: Get composer cache directory
        id: composer-cache
        run: echo "::set-output name=dir::$(composer config cache-files-dir)"

      - name: Cache dependencies
        uses: actions/cache@v2
        with:
          path: ${{ steps.composer-cache.outputs.dir }}
          key: ${{ matrix.php }}-composer-prefer-stable-${{ hashFiles('**/composer.json') }}
          restore-keys: ${{ matrix.php }}-composer-prefer-stable-${{ hashFiles('**/composer.json') }}

      - name: Install dependencies
        run: composer install --prefer-dist

      - name: Prepare configuration (1)
        run: mv .github/workflows-configs/rector.php rector.php

      - name: Prepare configuration (2)
        run: mv .github/workflows-configs/phpstan.neon.dist phpstan.neon.dist

      - name: Execute Rector
        run: vendor/bin/rector process src --dry-run
