name: Analysis

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  phpstan:
    name: PHPStan
    runs-on: ubuntu-latest
    strategy:
      max-parallel: 10
      matrix:
        php: ["7.4", "8.0", "8.1"]

    steps:
      - name: Set up PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php }}
          coverage: none
          extensions: mbstring

      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install dependencies
        run: composer update --no-interaction --no-progress

      - name: Prepare configuration
        run: mv $GITHUB_WORKSPACE/.github/workflows-configs/phpstan.neon.dist $GITHUB_WORKSPACE/phpstan.neon.dist

      - name: Execute PHPStan
        run: vendor/bin/phpstan analyze --no-progress

  psalm:
    name: Psalm
    runs-on: ubuntu-latest
    strategy:
      max-parallel: 10
      matrix:
        php: ["7.4", "8.0", "8.1"]

    steps:
      - name: Set up PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php }}
          coverage: none
          extensions: mbstring

      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install dependencies
        run: composer update --no-interaction --no-progress

      - name: Prepare configuration
        run: mv $GITHUB_WORKSPACE/.github/workflows-configs/psalm.xml.dist $GITHUB_WORKSPACE/psalm.xml.dist

      - name: Execute PHPStan
        run: vendor/bin/psalm

  phpinsights:
    name: PHPInsights
    runs-on: ubuntu-latest
    strategy:
      max-parallel: 10
      matrix:
        php: ["7.4", "8.0", "8.1"]

    steps:
      - name: Set up PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php }}
          coverage: none
          extensions: mbstring

      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install dependencies
        run: composer update --no-interaction --no-progress

      - name: Prepare configuration
        run: mv $GITHUB_WORKSPACE/.github/workflows-configs/phpinsights.php $GITHUB_WORKSPACE/phpinsights.php

      - name: Execute PHPInsights
        run: vendor/bin/phpinsights --no-interaction -v

  rector:
    name: Rector
    runs-on: ubuntu-latest
    strategy:
      max-parallel: 10
      matrix:
        php: ["7.4", "8.0", "8.1"]

    steps:
      - name: Set up PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php }}
          coverage: none
          extensions: mbstring

      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install dependencies
        run: composer update --no-interaction --no-progress

      - name: Prepare configuration (1)
        run: mv $GITHUB_WORKSPACE/.github/workflows-configs/rector.php $GITHUB_WORKSPACE/rector.php

      - name: Prepare configuration (2)
        run: mv $GITHUB_WORKSPACE/.github/workflows-configs/phpstan.neon.dist $GITHUB_WORKSPACE/phpstan.neon.dist

      - name: Execute Rector
        run: vendor/bin/rector process src --dry-run

  pest:
    name: Pest
    runs-on: ubuntu-latest
    strategy:
      max-parallel: 10
      matrix:
        php: ["7.4", "8.0", "8.1"]

    steps:
      - name: Set up PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php }}
          coverage: pcov
          extensions: mbstring

      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install dependencies
        run: composer update --no-interaction --no-progress

      - name: Prepare configuration
        run: mv $GITHUB_WORKSPACE/.github/workflows-configs/phpunit.xml.dist $GITHUB_WORKSPACE/phpunit.xml.dist

      - name: Execute Pest
        run: vendor/bin/pest --ci --coverage

  codecov:
    name: Codecov
    runs-on: ubuntu-latest

    steps:
      - name: Set up PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: 8.1
          coverage: pcov
          extensions: mbstring

      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install dependencies
        run: composer update --no-interaction --no-progress

      - name: Prepare configuration
        run: mv $GITHUB_WORKSPACE/.github/workflows-configs/phpunit.xml.dist $GITHUB_WORKSPACE/phpunit.xml.dist

      - name: Generate coverage report
        run: vendor/bin/pest --ci --coverage --coverage-clover coverage/coverage.xml

      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v2
        with:
          directory: coverage
