name: Analysis

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  dependencies:
    name: Dependencies
    runs-on: ubuntu-latest

    strategy:
      max-parallel: 10
      matrix:
        php: ["7.4", "8.0", "8.1"]

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up PHP ${{ matrix.php }}
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php }}
          coverage: pcov
          extensions: mbstring
        env:
          update: true
          COMPOSER_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Get composer cache directory
        id: composer-cache
        run: echo "::set-output name=dir::$(composer config cache-files-dir)"

      - name: Cache dependencies
        uses: actions/cache@v2
        with:
          path: ${{ steps.composer-cache.outputs.dir }}
          key: ${{ matrix.php }}-composer-${{ hashFiles('**/composer.json') }}

      - name: Install dependencies with composer
        run: composer update --no-ansi --no-interaction --no-progress --prefer-dist --prefer-stable

  configurations:
    name: Configuration
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Prepare configuration (rector.php)
        run: mv .github/workflows-configs/rector.php rector.php

      - name: Store coverage file (rector.php)
        uses: actions/upload-artifact@v3
        with:
          name: config-rector
          path: rector.php

      - name: Prepare configuration (phpstan.neon.dist)
        run: mv .github/workflows-configs/phpstan.neon.dist phpstan.neon.dist

      - name: Store coverage file (phpstan.neon.php)
        uses: actions/upload-artifact@v3
        with:
          name: config-phpstan
          path: phpstan.neon.php

      - name: Prepare configuration (phpunit.xml.dist)
        run: mv .github/workflows-configs/phpunit.xml.dist phpunit.xml.dist

      - name: Store coverage file (phpunit.xml.dist)
        uses: actions/upload-artifact@v3
        with:
          name: config-rector
          path: phpunit.xml.dist

      - name: Prepare configuration (psalm.xml.dist)
        run: mv .github/workflows-configs/psalm.xml.dist psalm.xml.dist

      - name: Store coverage file (psalm.xml.dist)
        uses: actions/upload-artifact@v3
        with:
          name: config-psalm
          path: psalm.xml.dist

      - name: Prepare configuration (pint.json)
        run: mv .github/workflows-configs/pint.json pint.json

      - name: Store coverage file (pint.json)
        uses: actions/upload-artifact@v3
        with:
          name: config-pint
          path: pint.json

  pest:
    name: Pest
    runs-on: ubuntu-latest
    continue-on-error: true
    needs: ["dependencies", "configurations"]

    strategy:
      max-parallel: 10
      matrix:
        php: ["7.4", "8.0", "8.1"]

    steps:
      - name: Set up PHP ${{ matrix.php }}
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php }}
          coverage: pcov
          extensions: mbstring
        env:
          update: true
          COMPOSER_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Checkout code
        uses: actions/checkout@v3

      - name: Get composer cache directory
        id: composer-cache
        run: echo "::set-output name=dir::$(composer config cache-files-dir)"

      - name: Cache dependencies
        uses: actions/cache@v2
        with:
          path: ${{ steps.composer-cache.outputs.dir }}
          key: ${{ matrix.php }}-composer-${{ hashFiles('**/composer.json') }}
          restore-keys: ${{ matrix.php }}-composer-${{ hashFiles('**/composer.json') }}

      - name: Install dependencies with composer
        run: composer install --prefer-dist

      - name: Prepare configuration (phpunit.xml.dist)
        uses: actions/download-artifact@v3
        with:
          name: config-phpunit
          path: phpunit.xml.dist

      - name: Execute Pest
        run: php -d memory_limit=512M vendor/bin/pest --coverage-clover coverage/coverage.xml

      - if: (matrix.php == '8.1')
        name: Store coverage file
        uses: actions/upload-artifact@v3
        with:
          name: code-coverage-report
          path: coverage/coverage.xml

  codecov:
    name: Codecov
    runs-on: ubuntu-latest
    needs: ["pest"]

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Recover code coverage file from Pest run
        uses: actions/download-artifact@v3
        with:
          name: code-coverage-report
          path: coverage/coverage.xml

      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v2
        with:
          directory: coverage

  phpstan:
    name: PHPStan
    runs-on: ubuntu-latest
    needs: ["dependencies", "configurations"]

    strategy:
      fail-fast: true
      max-parallel: 10
      matrix:
        php: ["7.4", "8.0", "8.1"]

    steps:
      - name: Set up PHP ${{ matrix.php }}
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php }}
          coverage: none
          extensions: mbstring
        env:
          update: true
          COMPOSER_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Checkout code
        uses: actions/checkout@v3

      - name: Get composer cache directory
        id: composer-cache
        run: echo "::set-output name=dir::$(composer config cache-files-dir)"

      - name: Cache dependencies
        uses: actions/cache@v2
        with:
          path: ${{ steps.composer-cache.outputs.dir }}
          key: ${{ matrix.php }}-composer-${{ hashFiles('**/composer.json') }}
          restore-keys: ${{ matrix.php }}-composer-${{ hashFiles('**/composer.json') }}

      - name: Install dependencies
        run: composer install --prefer-dist

      - name: Prepare configuration (phpstan.neon.dist)
        uses: actions/download-artifact@v3
        with:
          name: config-phpstan
          path: phpstan.neon.dist

      - name: Execute PHPStan
        run: vendor/bin/phpstan analyze --no-progress

  psalm:
    name: Psalm
    runs-on: ubuntu-latest
    needs: ["dependencies", "configurations"]

    strategy:
      fail-fast: true
      max-parallel: 10
      matrix:
        php: ["7.4", "8.0", "8.1"]

    steps:
      - name: Set up PHP ${{ matrix.php }}
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php }}
          coverage: none
          extensions: mbstring
        env:
          update: true
          COMPOSER_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Checkout code
        uses: actions/checkout@v3

      - name: Get composer cache directory
        id: composer-cache
        run: echo "::set-output name=dir::$(composer config cache-files-dir)"

      - name: Cache dependencies
        uses: actions/cache@v2
        with:
          path: ${{ steps.composer-cache.outputs.dir }}
          key: ${{ matrix.php }}-composer-${{ hashFiles('**/composer.json') }}
          restore-keys: ${{ matrix.php }}-composer-${{ hashFiles('**/composer.json') }}

      - name: Install dependencies
        run: composer install --prefer-dist

      - name: Prepare configuration (psalm.xml.dist)
        uses: actions/download-artifact@v3
        with:
          name: config-psalm
          path: psalm.xml.dist

      - name: Execute Psalm
        run: vendor/bin/psalm

  pint:
    name: Laravel Pint
    runs-on: ubuntu-latest
    needs: ["dependencies", "configurations"]

    strategy:
      fail-fast: true
      max-parallel: 10
      matrix:
        php: ["8.0", "8.1"]

    steps:
      - name: Set up PHP ${{ matrix.php }}
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php }}
          coverage: none
          extensions: mbstring
        env:
          update: true
          COMPOSER_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Checkout code
        uses: actions/checkout@v3

      - name: Get composer cache directory
        id: composer-cache
        run: echo "::set-output name=dir::$(composer config cache-files-dir)"

      - name: Cache dependencies
        uses: actions/cache@v2
        with:
          path: ${{ steps.composer-cache.outputs.dir }}
          key: ${{ matrix.php }}-composer-${{ hashFiles('**/composer.json') }}
          restore-keys: ${{ matrix.php }}-composer-${{ hashFiles('**/composer.json') }}

      - name: Install dependencies
        run: composer install --prefer-dist

      - name: Install Laravel Pint
        run: composer require laravel/pint:* --dev --with-all-dependencies

      - name: Execute Laravel Pint
        run: vendor/bin/pint --preset psr12 --test

  rector:
    name: Rector
    runs-on: ubuntu-latest
    needs: ["dependencies", "configurations"]

    strategy:
      fail-fast: true
      max-parallel: 10
      matrix:
        php: ["7.4", "8.0", "8.1"]

    steps:
      - name: Set up PHP ${{ matrix.php }}
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php }}
          coverage: none
          extensions: mbstring
        env:
          update: true
          COMPOSER_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Checkout code
        uses: actions/checkout@v3

      - name: Get composer cache directory
        id: composer-cache
        run: echo "::set-output name=dir::$(composer config cache-files-dir)"

      - name: Cache dependencies
        uses: actions/cache@v2
        with:
          path: ${{ steps.composer-cache.outputs.dir }}
          key: ${{ matrix.php }}-composer-${{ hashFiles('**/composer.json') }}
          restore-keys: ${{ matrix.php }}-composer-${{ hashFiles('**/composer.json') }}

      - name: Install dependencies
        run: composer install --prefer-dist

      - name: Prepare configuration (rector.php)
        uses: actions/download-artifact@v3
        with:
          name: config-rector
          path: rector.php

      - name: Prepare configuration (phpstan.neon.dist)
        uses: actions/download-artifact@v3
        with:
          name: config-phpstan
          path: phpstan.neon.dist

      - name: Execute Rector
        run: vendor/bin/rector process src --dry-run
