name: "Pull Request / Run Checks"

on:
  workflow_run:
    workflows:
      - "Pull Request / Labeled: Vetted"
    types:
      - completed

permissions:
  checks: write

jobs:
  pull-request:
    name: "Details"
    uses: auth0/auth0-PHP/.github/workflows/common.pr-details.get.yml@main

  check:
    needs: pull-request

    name: "Run"
    runs-on: ubuntu-latest

    steps:
      - uses: actions/github-script@v6
        with:
          script: |
            await github.rest.checks.create({
              owner: context.repo.owner,
              repo: context.repo.repo,
              head_sha: '${{ needs.pull-request.outputs.sha }}',
              name: "CI / Composer Normalize",
              status: "in_progress"
            });

            await github.rest.checks.create({
              owner: context.repo.owner,
              repo: context.repo.repo,
              head_sha: '${{ needs.pull-request.outputs.sha }}',
              name: "CI / Composer Validate",
              status: "in_progress"
            });

            await github.rest.checks.create({
              owner: context.repo.owner,
              repo: context.repo.repo,
              head_sha: '${{ needs.pull-request.outputs.sha }}',
              name: "CI / PEST",
              status: "in_progress"
            });

            await github.rest.checks.create({
              owner: context.repo.owner,
              repo: context.repo.repo,
              head_sha: '${{ needs.pull-request.outputs.sha }}',
              name: "CI / PHP CS Fixer",
              status: "in_progress"
            });

            await github.rest.checks.create({
              owner: context.repo.owner,
              repo: context.repo.repo,
              head_sha: '${{ needs.pull-request.outputs.sha }}',
              name: "CI / PHPStan",
              status: "in_progress"
            });

            await github.rest.checks.create({
              owner: context.repo.owner,
              repo: context.repo.repo,
              head_sha: '${{ needs.pull-request.outputs.sha }}',
              name: "CI / Psalm",
              status: "in_progress"
            });

            await github.rest.checks.create({
              owner: context.repo.owner,
              repo: context.repo.repo,
              head_sha: '${{ needs.pull-request.outputs.sha }}',
              name: "CI / Rector",
              status: "in_progress"
            });

            await github.rest.checks.create({
              owner: context.repo.owner,
              repo: context.repo.repo,
              head_sha: '${{ needs.pull-request.outputs.sha }}',
              name: "CI / Semgrep",
              status: "in_progress"
            });

            await github.rest.checks.create({
              owner: context.repo.owner,
              repo: context.repo.repo,
              head_sha: '${{ needs.pull-request.outputs.sha }}',
              name: "CI / Snyk",
              status: "in_progress"
            });
