name: "Pull Request / Unlabelled: Unvetted"

on:
  workflow_run:
    workflows:
      - "Pull Request / Unlabelled"
    types:
      - completed

permissions: {}

concurrency:
  group: ${{ github.workflow_ref }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

jobs:
  check:
    name: "Maintainer Approval"
    runs-on: ubuntu-latest

    steps:
      # Dependabot. Success.
      - if: ${{ github.actor == 'dependabot[bot]' }}
        run: exit 0

      # Is having the 'Vetted' label removed. Success.
      - if: ${{ github.event.label.name == 'Vetted' }}
        run: exit 0
