name: "Pull Request / Modified"

# -----------------------------------------------------------------------------
#
# Fired when a pull request's head branch is updated.
#
# -----------------------------------------------------------------------------

on:
  pull_request:
    types:
      - opened
      - synchronize
      - closed
      - reopened

permissions: {}

jobs:
  check:
    name: "Maintainer Approval"
    runs-on: ubuntu-latest

    steps:
      - name: Save PR details
        env:
          PR_NUMBER: ${{ github.event.number }}
          PR_SHA: ${{ github.sha }}
        run: |
          mkdir -p ./pr
          echo $PR_NUMBER > ./pr/pr_number
          echo $PR_SHA > ./pr/pr_sha

      - uses: actions/upload-artifact@v3
        with:
          name: pr_number
          path: pr/

      - run: exit 0
