name: "Pull Request / Run Checks"

on:
  workflow_run:
    workflows:
      - "Pull Request / Labeled: Vetted"
      - "Pull Request / Unlabelled: Unvetted"
    types:
      - completed

permissions:
  issues: write
  pull-requests: write

jobs:
  check:
    name: "Maintainer Approval"
    runs-on: ubuntu-latest

    steps:
      - uses: actions/github-script@v6
        with:
          script: |
            await github.rest.checks.create({
              owner: context.repo.owner,
              repo: context.repo.repo,
              head_sha: context.sha,
              name: "Composer Normalize",
              status: "in_progress"
            });

      - uses: actions/github-script@v6
        with:
          script: |
            await github.rest.checks.create({
              owner: context.repo.owner,
              repo: context.repo.repo,
              head_sha: context.sha,
              name: "Composer Validate",
              status: "in_progress"
            });

      - uses: actions/github-script@v6
        with:
          script: |
            await github.rest.checks.create({
              owner: context.repo.owner,
              repo: context.repo.repo,
              head_sha: context.sha,
              name: "PEST",
              status: "in_progress"
            });


      - uses: actions/github-script@v6
        with:
          script: |
            await github.rest.checks.create({
              owner: context.repo.owner,
              repo: context.repo.repo,
              head_sha: context.sha,
              name: "PHP CS Fixer",
              status: "in_progress"
            });

      - uses: actions/github-script@v6
        with:
          script: |
            await github.rest.checks.create({
              owner: context.repo.owner,
              repo: context.repo.repo,
              head_sha: context.sha,
              name: "PHPStan",
              status: "in_progress"
            });

      - uses: actions/github-script@v6
        with:
          script: |
            await github.rest.checks.create({
              owner: context.repo.owner,
              repo: context.repo.repo,
              head_sha: context.sha,
              name: "Psalm",
              status: "in_progress"
            });

      - uses: actions/github-script@v6
        with:
          script: |
            await github.rest.checks.create({
              owner: context.repo.owner,
              repo: context.repo.repo,
              head_sha: context.sha,
              name: "Rector",
              status: "in_progress"
            });

      - uses: actions/github-script@v6
        with:
          script: |
            await github.rest.checks.create({
              owner: context.repo.owner,
              repo: context.repo.repo,
              head_sha: context.sha,
              name: "Semgrep",
              status: "in_progress"
            });

      - uses: actions/github-script@v6
        with:
          script: |
            await github.rest.checks.create({
              owner: context.repo.owner,
              repo: context.repo.repo,
              head_sha: context.sha,
              name: "Snyk",
              status: "in_progress"
            });
