name: "Pull Request / Modified"

# -----------------------------------------------------------------------------
#
# Fired when a pull request's head branch is updated.
#
# -----------------------------------------------------------------------------

on:
  pull_request:
    types:
      - opened
      - synchronize
      - closed
      - reopened

permissions: {}

jobs:
  pull-request:
    uses: auth0/auth0-PHP/.github/workflows/common.pr-details.save.yml@main

  check:
    needs: pull-request

    name: "Maintainer Approval"
    runs-on: ubuntu-latest

    steps:
      - run: exit 0
