name: "Create a Check"

on:
  workflow_call:
    inputs:
      name:
        description: "The name of the check"
        required: true
        type: string
      status:
        description: "the status of the check `queued`, `in_progress` or `completed`"
        required: true
        type: string
      title:
        description: "the title to put on the check panel"
        required: true
        type: string
      summary:
        description: "The summary of the check runs current result"
        required: true
        type: string
      details:
        description: "The details for the check"
        required: false
        type: string
    outputs:
      check_run_id:
        description: "contains the check run id of the check created "
        value: ${{ jobs.check.outputs.result }}

jobs:
  check:
    name: "Prepare"
    runs-on: ubuntu-latest

    outputs:
      result: ${{ steps.create.outputs }}

    steps:
      - uses: actions/github-script@v6
        id: create
        with:
          return-encoding: string
          script: |
            let body = {
              owner: process.env.GITHUB_REPOSITORY.split('/')[0],
              repo: process.env.GITHUB_REPOSITORY.split('/')[1],
              name: ${{ inputs.name || github.event.repository.name }},
              head_sha: process.env.GITHUB_SHA,
              status: ${{ inputs.status }},
              output: {
                title: ${{ inputs.title }},
                summary: ${{ inputs.summary }},
                text: ${{ inputs.details }}
              }
            };

            const check = await github.rest.checks.create(body);
            return check.data.id
