name: "Pull Request / Checks"

on:
  merge_group:
  push:
    branches:
      - main
  pull_request:
    types:
      - labeled

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

permissions:
  pull-requests: read

jobs:
  check:
    name: "Maintainer Approval"
    runs-on: ubuntu-latest

    steps:
      - if: ${{ github.actor == 'dependabot[bot]' }}
        run: exit 0

      - if: ${{ github.event_name != 'pull_request' }}
        run: exit 0

      - if: ${{ github.event.pull_request.head.repo.full_name != github.event.pull_request.base.repo.full_name }}
        run: exit 0

      - if: ${{ github.event.label.name == 'Vetted' }}
        run: exit 0
