name: "Pull Request / Unlabelled: Unvetted"

on:
  workflow_run:
    workflows:
      - "Pull Request / Labeled"
    types:
      - completed

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

permissions: {}

jobs:
  check:
    if: ${{ github.event_name == 'pull_request' }}

    name: "Maintainer Approval"
    runs-on: ubuntu-latest

    steps:
      # Dependabot. Success.
      - if: ${{ github.actor == 'dependabot[bot]' }}
        run: exit 0

      # Is having the 'Vetted' label removed. Success.
      - if: ${{ github.event.label.name == 'Vetted' }}
        run: exit 0

      # Otherwise, fail.
      # - run: exit 1
