name: "Pull Request / Run Checks"

on:
  workflow_run:
    workflows:
      - "Pull Request / Labeled: Vetted"
    types:
      - completed

permissions:
  checks: write

concurrency:
  group: "common.pull-request.run-checks-${{ github.ref }}"
  cancel-in-progress: true

jobs:
  pull-request:
    name: "Details"
    uses: "./.github/workflows/common.pr-details.get.yml"

  check:
    needs: pull-request

    name: "Run"
    runs-on: ubuntu-latest

    steps:
      - run: exit 0
