name: "Pull Request / Run Checks"

on:
  workflow_run:
    workflows:
      - "Pull Request / Labeled: Vetted"
    types:
      - completed

permissions:
  checks: write

jobs:
  pull-request:
    name: "Details"
    uses: auth0/auth0-PHP/.github/workflows/common.pr-details.get.yml@main

  check:
    needs: pull-request

    name: "Run"
    runs-on: ubuntu-latest

    steps:
      - run: exit 0
