name: "Pull Request / Run Checks"

on:
  workflow_run:
    workflows:
      - "Pull Request / Labeled: Vetted"
    types:
      - completed

permissions:
  checks: write

jobs:
  pull-request:
    name: "Get"
    uses: auth0/auth0-PHP/.github/workflows/common.pr-details.get.yml@main

  check:
    needs: pull-request

    name: "Run"
    runs-on: ubuntu-latest

    steps:
      - uses: actions/github-script@v6
        with:
          script: |
            let fs = require('fs');
            let pr_sha = fs.readFileSync('./pr_sha', 'utf8');

            await github.rest.checks.create({
              owner: context.repo.owner,
              repo: context.repo.repo,
              head_sha: needs.pull-request.outputs.sha,
              name: "Composer Normalize",
              status: "in_progress"
            });

      - uses: actions/github-script@v6
        with:
          script: |
            await github.rest.checks.create({
              owner: context.repo.owner,
              repo: context.repo.repo,
              head_sha: needs.pull-request.outputs.sha,
              name: "Composer Validate",
              status: "in_progress"
            });

      - uses: actions/github-script@v6
        with:
          script: |
            await github.rest.checks.create({
              owner: context.repo.owner,
              repo: context.repo.repo,
              head_sha: needs.pull-request.outputs.sha,
              name: "PEST",
              status: "in_progress"
            });

      - uses: actions/github-script@v6
        with:
          script: |
            await github.rest.checks.create({
              owner: context.repo.owner,
              repo: context.repo.repo,
              head_sha: needs.pull-request.outputs.sha,
              name: "PHP CS Fixer",
              status: "in_progress"
            });

      - uses: actions/github-script@v6
        with:
          script: |
            await github.rest.checks.create({
              owner: context.repo.owner,
              repo: context.repo.repo,
              head_sha: needs.pull-request.outputs.sha,
              name: "PHPStan",
              status: "in_progress"
            });

      - uses: actions/github-script@v6
        with:
          script: |
            await github.rest.checks.create({
              owner: context.repo.owner,
              repo: context.repo.repo,
              head_sha: needs.pull-request.outputs.sha,
              name: "Psalm",
              status: "in_progress"
            });

      - uses: actions/github-script@v6
        with:
          script: |
            await github.rest.checks.create({
              owner: context.repo.owner,
              repo: context.repo.repo,
              head_sha: needs.pull-request.outputs.sha,
              name: "Rector",
              status: "in_progress"
            });

      - uses: actions/github-script@v6
        with:
          script: |
            await github.rest.checks.create({
              owner: context.repo.owner,
              repo: context.repo.repo,
              head_sha: needs.pull-request.outputs.sha,
              name: "Semgrep",
              status: "in_progress"
            });

      - uses: actions/github-script@v6
        with:
          script: |
            await github.rest.checks.create({
              owner: context.repo.owner,
              repo: context.repo.repo,
              head_sha: needs.pull-request.outputs.sha,3
              name: "Snyk",
              status: "in_progress"
            });
