name: "Pull Request / Modified"

# -----------------------------------------------------------------------------
#
# Fired when a pull request's head branch is updated.
#
# -----------------------------------------------------------------------------

on:
  pull_request:
    types:
      - opened
      - synchronize
      - closed
      - reopened

permissions: {}

jobs:
  check:
    name: "Maintainer Approval"
    runs-on: ubuntu-latest

    steps:
      - uses: ./.github/workflows/common.pr-details.save.yml
        with:
          number: ${{ github.event.number }}
          sha: ${{ github.sha }}

      - run: exit 0
