name: Get Pull Request Details

on:
  workflow_call:
    outputs:
      number:
        value: ${{ jobs.get.outputs.pr_number }}
      sha:
        value: ${{ jobs.get.outputs.pr_sha }}

jobs:
  get:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - uses: actions/download-artifact@v3
        with:
          name: pr_details.zip

      - run: unzip pr_details.zip

      - uses: actions/github-script@v6
        with:
          script: |
            let fs = require('fs');
            let number = Number(fs.readFileSync('./number'));
            let sha = fs.readFileSync('./sha', 'utf-8');

            core.setOutput('number', number);
            core.setOutput('sha', sha);

      - run: exit 0
