name: "Snyk (Scheduled)"

# This workflow will run after a push to the main branch and as a scheduled job.

on:
  push:
    branches:
      - main
  schedule:
    - cron: "30 0 1,15 * *"

permissions: {}

jobs:
  snyk:
    name: "Scan"
    runs-on: ubuntu-latest

    steps:
      - uses: shivammathur/setup-php@4bd44f22a98a19e0950cbad5f31095157cc9621b # pin@2.25.4
        with:
          php-version: "8.1"
          coverage: none
          extensions: mbstring
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - uses: actions/checkout@v3

      - run: composer install --no-progress

      - uses: snyk/actions/php@b98d498629f1c368650224d6d212bf7dfa89e4bf # pin@0.4.0
        continue-on-error: true
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
