name: "CI"

# This workflow will run after a merge to the main branch from a pull request.

on:
  merge_group:
  push:
    branches:
      - main

permissions:
  contents: read

jobs:
  phpstan:
    name: "PHPStan"
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - uses: shivammathur/setup-php@4bd44f22a98a19e0950cbad5f31095157cc9621b # pin@2.25.4
        with:
          php-version: ${{ env.PHP_VERSION }}

      - run: composer install --no-progress

      - run: vendor/bin/phpstan analyze --no-ansi --no-progress --debug
