name: "Rector"

on:
  pull_request:
  merge_group:
  push:
    branches:
      - main

permissions: {}

jobs:
  rector:
    name: "Scan"
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - uses: shivammathur/setup-php@4bd44f22a98a19e0950cbad5f31095157cc9621b # pin@2.25.4
        with:
          php-version: "8.1"

      - run: composer install --no-progress

      - run: vendor/bin/rector process --dry-run
