name: "Semgrep"

on:
  workflow_run:
    workflows: ["Pull Request Changes"]
    types:
      - completed

permissions: {}

jobs:
  wait:
    name: "Scan"
    runs-on: ubuntu-latest

    container:
      image: returntocorp/semgrep

    steps:
      - uses: actions/checkout@v3
        with:
          ref: ${{ github.event.pull_request.head.sha }}
          github-token: ${{ secrets.GITHUB_TOKEN }}

      - run: semgrep ci
        env:
          SEMGREP_APP_TOKEN: ${{ secrets.SEMGREP_APP_TOKEN }}
