name: "CI"

# This workflow will run after a pull request is opened or updated, assuming the pull request is labeled with "Vetted".

on:
  workflow_run:
    workflows:
      - "Pull Request / Run Checks"
    types:
      - completed

permissions:
  contents: read
  checks: write

concurrency:
  group: "pull-request.pest-${{ github.ref }}"
  cancel-in-progress: true

jobs:
  pull-request:
    name: "Details"
    uses: auth0/auth0-PHP/.github/workflows/common.pr-details.get.yml@main

  pest:
    needs: pull-request

    name: "PEST"
    runs-on: ubuntu-latest

    if: ${{ github.event.workflow_run.conclusion == 'success' }}

    steps:
      - uses: actions/github-script@v6
        with:
          script: |
            await github.rest.checks.create({
              owner: context.repo.owner,
              repo: context.repo.repo,
              head_sha: '${{ needs.pull-request.outputs.sha }}',
              name: "PEST",
              status: "in_progress"
            });

      - uses: actions/checkout@v3
        with:
          ref: ${{ github.event.pull_request.head.sha }}
          github-token: ${{ secrets.GITHUB_TOKEN }}

      - uses: shivammathur/setup-php@4bd44f22a98a19e0950cbad5f31095157cc9621b # pin@2.25.4
        with:
          php-version: ${{ env.PHP_VERSION }}
          coverage: pcov
          extensions: mbstring
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - run: composer install --no-progress

      - run: vendor/bin/pest --order-by random --fail-on-risky --stop-on-defect --coverage --parallel

      - uses: codecov/codecov-action@eaaf4bedf32dbdc6b720b63067d99c4d77d6047d # pin@3.1.4
        with:
          directory: ./coverage/
          flags: unittests

      - uses: actions/github-script@v6
        with:
          script: |
            await github.rest.checks.create({
              owner: context.repo.owner,
              repo: context.repo.repo,
              head_sha: '${{ needs.pull-request.outputs.sha }}',
              name: "PEST",
              status: "completed",
              conclusion: 'success'
            });
