name: "Pull Request CI"

# This workflow will run after a pull request is opened or updated, assuming the pull request is labeled with "Vetted".

on:
  workflow_run:
    workflows:
      - "Pull Request / Run Checks"
    types:
      - completed

permissions:
  contents: read
  checks: write

concurrency:
  group: "pull-request.phpstan-${{ github.ref }}"
  cancel-in-progress: true

jobs:
  pull-request:
    name: "Details"
    uses: "./.github/workflows/common.pr-details.get.yml"

  phpstan:
    needs: pull-request

    name: "PHPStan"
    runs-on: ubuntu-latest

    if: ${{ github.event.workflow_run.conclusion == 'success' }}

    steps:
      - id: create-check
        uses: actions/github-script@v6
        with:
          result-encoding: string
          script: |
            const check = await github.rest.checks.create({
              owner: context.repo.owner,
              repo: context.repo.repo,
              head_sha: '${{ needs.pull-request.outputs.sha }}',
              name: "PHPStan",
              status: "in_progress"
            })
            return check.data.id

      - uses: actions/checkout@v3
        with:
          ref: ${{ github.event.pull_request.head.sha }}
          github-token: ${{ secrets.GITHUB_TOKEN }}

      - uses: shivammathur/setup-php@4bd44f22a98a19e0950cbad5f31095157cc9621b # pin@2.25.4
        with:
          php-version: ${{ env.PHP_VERSION }}
          coverage: none
          extensions: mbstring
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - run: composer install --no-progress

      - run: vendor/bin/phpstan analyze --no-ansi --no-progress --debug

      - uses: actions/github-script@v6
        env:
          parameter_url: "${{ github.event.workflow_run.html_url }}"
        with:
          script: |
            await github.rest.checks.update({
              owner: context.repo.owner,
              repo: context.repo.repo,
              check_run_id: '${{steps.create-check.outputs.result}}',
              name: "PHPStan",
              status: "completed",
              conclusion: "${{ github.event.workflow_run.conclusion }}",
              details_url: process.env.parameter_url
            });
