name: "Pull Request CI Status"

on:
  workflow_run:
    workflows:
      - "Pull Request CI"
    types:
      - completed

permissions:
  contents: read
  checks: write

concurrency:
  group: "pull-request.checks-${{ github.ref }}"
  cancel-in-progress: true

jobs:
  pull-request:
    name: "Details"
    uses: "./.github/workflows/common.pr-details.get.yml"

  check:
    needs: pull-request

    name: "Passed"
    runs-on: ubuntu-latest

    steps:
      - id: request-status
        uses: octokit/graphql-action@v2.x
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          query: |
            query status($owner: String!, $repo: String!, $pull_number: Int!) {
              repository(owner: $owner, name:$repo) {
                pullRequest(number:$pull_number) {
                  commits(last: 1) {
                    nodes {
                      commit {
                        statusCheckRollup {
                          state
                        }
                      }
                    }
                  }
                }
              }
            }
          owner: ${{ github.event.repository.owner.name }}
          repo: ${{ github.event.repository.name }}
          pull_number: ${{ github.event.repository.name }}

      - id: extract-status
        uses: actions/github-script@v6
        with:
          script: |
            const [{ commit: lastCommit }] = ${{ steps.request-status.outputs.data }};
            return lastCommit.statusCheckRollup.state === "SUCCESS"

      - id: report-failure
        if: ${{ !steps.extract-status.outputs.result }}
        run: exit 1

      - id: report-success
        run: exit 0
