name: "CI Checks"

# This workflow will be triggered after each CI workflow completes.

on:
  workflow_run:
    workflows:
      - "CI"
    types:
      - completed

permissions:
  contents: read
  checks: write

concurrency:
  group: ${{ github.workflow_ref }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

jobs:
  on-success:
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    steps:
      - run: echo 'The triggering workflow passed'

  on-failure:
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'failure' }}
    steps:
      - run: echo 'The triggering workflow failed'

  pest:
    name: "Passed"
    runs-on: ubuntu-latest

    steps:
      - run: exit 0
