name: "PEST Unit Tests"

# This workflow will run after a pull request is opened or updated, assuming the pull request is labeled with "Vetted".

on:
  workflow_run:
    workflows:
      - "Pull Request / Run Checks"
    types:
      - completed

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

permissions:
  contents: read

jobs:
  pest:
    if: ${{ github.event_name == 'pull_request' }}

    name: "Run Checks"
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
        with:
          ref: ${{ github.event.pull_request.head.sha }}
          github-token: ${{ secrets.GITHUB_TOKEN }}

      - uses: shivammathur/setup-php@4bd44f22a98a19e0950cbad5f31095157cc9621b # pin@2.25.4
        with:
          php-version: ${{ env.PHP_VERSION }}
          coverage: pcov
          extensions: mbstring
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - run: composer install --no-progress

      - run: vendor/bin/pest --order-by random --fail-on-risky --stop-on-defect --coverage --parallel --min 100

      - uses: codecov/codecov-action@eaaf4bedf32dbdc6b720b63067d99c4d77d6047d # pin@3.1.4
        with:
          directory: ./coverage/
          flags: unittests
