name: "CI Checks"

# This workflow will be triggered after each CI workflow completes.

on:
  workflow_run:
    workflows:
      - "CI"
    types:
      - completed

permissions:
  contents: read
  checks: write

concurrency:
  group: "pull-request.checks-${{ github.ref }}"
  cancel-in-progress: true

jobs:
  on-completed:
    name: "Passed"
    runs-on: ubuntu-latest

    steps:
      - run: exit 0
