name: Contributors

on:
  schedule:
    - cron: "30 1 * * *"

permissions:
  issues: write
  pull-requests: write

jobs:
  close-issues:
    name: Close Issues
    runs-on: ubuntu-latest

    steps:
      - uses: actions/stale@v6
        with:
          days-before-stale: 7
          days-before-close: 14
          repo-token: ${{ secrets.GITHUB_TOKEN }}
