on:
  pull_request_target:
    types:
      - closed
      - reopened
      - converted_to_draft
      - review_requested
      - review_request_removed
      - synchronize

jobs:
  rep-cleanup:
    name: Issue/PR Cleanup
    runs-on: ubuntu-latest

    permissions:
      issues: write
      pull-requests: write

    steps:
      - uses: actions/github-script@v6
        with:
          script: |
            try {
              labels = await github.rest.issues.listLabelsOnIssue({
                issue_number: context.issue.number,
                owner: context.repo.owner,
                repo: context.repo.repo
              })

              if (labels.data.some(label => label.name === 'run')) {
                github.rest.issues.removeLabel({
                  owner: context.repo.owner,
                  repo: context.repo.repo,
                  issue_number: context.issue.number,
                  name: 'run'
                });
              }
            } catch (error) {
              console.error(error);
            }
