name: Style

on:
  pull_request_target:
    types: [labeled]

permissions:
  contents: write
  pull-requests: write

jobs:
  configuration:
    name: Configure
    runs-on: ubuntu-latest
    outputs:
      allow-label: ${{ env.ALLOW_LABEL }}
    steps:
      - name: Save state
        run: |
          echo "ALLOW_LABEL=Status: 🤞 Run Tests" >> $GITHUB_ENV

  style-pint:
    name: Pint
    needs: configuration
    runs-on: ubuntu-latest

    # Determine if the label is present.
    if: github.event.label.name == needs.configuration.outputs.allow-label

    strategy:
      fail-fast: true
      max-parallel: 10
      matrix:
        php: ["8.0", "8.1", "8.2"]

    steps:
      - uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php }}
          coverage: none
          extensions: mbstring, openssl
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - uses: actions/checkout@v3

      - run: composer update --no-ansi --no-interaction --no-progress --prefer-dist --prefer-stable
      - run: vendor/bin/pint --test

  style-rector:
    name: Rector
    needs: configuration
    runs-on: ubuntu-latest

    # Determine if the label is present.
    if: github.event.label.name == needs.configuration.outputs.allow-label

    strategy:
      fail-fast: true
      max-parallel: 10
      matrix:
        php: ["8.0", "8.1", "8.2"]

    steps:
      - uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php }}
          coverage: none
          extensions: mbstring, openssl
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - uses: actions/checkout@v3

      - run: composer update --no-ansi --no-interaction --no-progress --prefer-dist --prefer-stable
      - run: vendor/bin/rector process src --dry-run
