name: Style

on:
  pull_request_target:
    types: [labeled]

permissions:
  contents: write
  pull-requests: write

jobs:
  style-pint:
    if: github.event.label.name == "Status:\ 🤞 Run Tests"
    name: Pint
    runs-on: ubuntu-latest

    strategy:
      fail-fast: true
      max-parallel: 10
      matrix:
        php: ["8.0", "8.1", "8.2"]

    steps:
      - uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php }}
          coverage: none
          extensions: mbstring, openssl
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - uses: actions/checkout@v3

      - run: composer update --no-ansi --no-interaction --no-progress --prefer-dist --prefer-stable
      - run: vendor/bin/pint --test

  style-rector:
    if: github.event.label.name == "Status:\ 🤞 Run Tests"
    name: Rector
    runs-on: ubuntu-latest

    strategy:
      fail-fast: true
      max-parallel: 10
      matrix:
        php: ["8.0", "8.1", "8.2"]

    steps:
      - uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php }}
          coverage: none
          extensions: mbstring, openssl
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - uses: actions/checkout@v3
        with:
          ref: github.event.pull_request.head.sha

      - run: composer update --no-ansi --no-interaction --no-progress --prefer-dist --prefer-stable
      - run: vendor/bin/rector process src --dry-run
